name: Publish to npm

on:
  push:
    branches:
      - main # This workflow runs when code is pushed (or merged) into the 'main' branch

# Define environment variables that can be used across jobs/steps.
env:
  NODE_VERSION: '20.x' # Use a Node.js LTS version, e.g., '20.x' or 'lts/*'

jobs:
  publish:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    # Set permissions for the GITHUB_TOKEN
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      # Step 1: Checkout the repository code.
      - name: Checkout repository
        uses: actions/checkout@v4 # Action to checkout your repository code

      # Step 2: Set up Node.js environment.
      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          # node-version: '18.x' # Or '20.x' or 'lts/*', choose your preferred LTS Node.js version
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://registry.npmjs.org' # Specifies the npm registry

      # Step 3: Install project dependencies.
      - name: Install dependencies
        run: npm ci # 'npm ci' is preferred over 'npm install' in CI environments for clean installs based on package-lock.json

      # Step 4: Run tests.
      # This step is crucial. If 'npm run test' fails (returns a non-zero exit code),
      # the workflow will stop here, and subsequent steps (build and publish) will not run.
      # - name: Run tests
       # run: npm run test

      # Step 4: Run the build process.
      # This step will only execute if the 'Run tests' step passed.
      - name: Build project
        run: npm run build # Your build script that generates the 'dist' folder

      # Step 5: Check if the version already exists on npm (optional but recommended safety check)
      - name: Check for existing npm version
        id: check_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          PACKAGE_NAME=$(node -p "require('./package.json').name")
          echo "Checking version $VERSION for $PACKAGE_NAME"
          if npm view "$PACKAGE_NAME@$VERSION" >/dev/null 2>&1; then
            echo "::set-output name=version_exists::true"
            echo "Version $VERSION already exists on npm. Skipping publish."
          else
            echo "::set-output name=version_exists::false"
            echo "Version $VERSION does not exist on npm. Proceeding with publish."
          fi
        shell: bash

      # Step 6: Publish the package to npm.
      # This step will only execute if all previous steps (including tests and build) passed,
      # AND if the version doesn't already exist on npm.
      - name: Publish to npm
        if: steps.check_version.outputs.version_exists == 'false'
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # Use a GitHub Secret for your npm token
